# Generated by Django 5.0.6 on 2024-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('size', 'size'), ('colour', 'colour')], max_length=100),
        ),
    ]
